apiVersion: cloudscale.crossplane.io/v1alpha1
kind: S3Bucket
metadata:
  name: s3bucket-sample
spec:
  display_name: testBucket
  tags:
    test: one
  writeConnectionSecretToRef:
    name: s3sample-cred
    namespace: crossplane-cloudscale
  providerRef:
    name: cloudscale-provider-sample
  reclaimPolicy: Delete
