apiVersion: storage.cloudscale.crossplane.io/v1alpha1
kind: S3Bucket
metadata:
  name: s3bucket-sample
spec:
  forProvider:
    nameFormat: testBucket
    cannedACL: private
    tags:
      test: one
  writeConnectionSecretToRef:
    name: s3sample-cred
    namespace: crossplane-cloudscale
  providerRef:
    name: cloudscale-provider-sample
  reclaimPolicy: Delete
