apiVersion: cloudscale.syn.vshn.ch/v1alpha1
kind: S3BucketClass
metadata:
  name: s3bucketclass-sample
specTemplate:
  nameFormat: crossplane-%s
  providerRef:
    name: cloudscale-provider-sample
  writeConnectionSecretsToNamespace: nonexistent
  reclaimPolicy: Delete
  tags:
    managed-by: crossplane
