apiVersion: apps/v1
kind: Deployment
metadata:
  name: "stack-cloudscale"
  labels:
    core.crossplane.io/name: "stack-cloudscale"
spec:
  selector:
    matchLabels:
      core.crossplane.io/name: "stack-cloudscale"
  replicas: 1
  template:
    metadata:
      name: "stack-cloudscale-controller"
      labels:
        core.crossplane.io/name: "stack-cloudscale"
    spec:
      containers:
      - name: "stack-cloudscale-controller"
        image: docker.io/vshn/stack-cloudscale:v0.0.1
        imagePullPolicy: Always
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
